### ISSUE TITLE
no pip release?

### ISSUE THREAD

**Issue by YiuTerran** [huaweicloud/huaweicloud-sdk-python-obs#2]
Please release SDK to pypi.

**Comment by 864546664** [comment]
你是中国人吧，下了源文件用python setup.py install指令安装就行了

**Comment by Asa-Lee** [comment]
> Please release SDK to pypi.

https://pypi.org/project/esdk-obs-python/

**Comment by YiuTerran** [comment]
@Asa-Lee thanks~

**Comment by cupen** [comment]
补充到 README 了，见 #9 
cc @Asa-Lee  

btw: @864546664  中国人也有用 pypi 的啊，加上镜像会快很多。:smile:
